items:
  # SPC: command-palette:open
  SPC: darlal-switcher-plus:switcher-plus:open
  ";": darlal-switcher-plus:switcher-plus:open-commands
  TAB: editor:focus
  /: global-search:open
  ",": editor:context-menu
  P: app:go-back
  N: app:go-forward
  "\\": workspace:split-vertical
  "-": workspace:split-horizontal
  h: editor:focus-left
  l: editor:focus-right
  k: editor:focus-top
  j: editor:focus-bottom
  e: darlal-switcher-plus:switcher-plus:open-symbols-active
  g: darlal-switcher-plus:switcher-plus:open-related-items-active

  B: darlal-switcher-plus:switcher-plus:open-editors
  b:
    description: Buffer
    items:
      b: darlal-switcher-plus:switcher-plus:open-editors
      d: workspace:close
      D: workspace:close-others
      n: workspace:next-tab
      p: workspace:previous-tab
      r: workspace:rename-tab
      s: workspace:save-all
      S: workspace:save-all-and-close
      t: workspace:toggle-pin
      w: workspace:close-window
      W: workspace:move-to-new-window
      f: darlal-switcher-plus:switcher-plus:open-starred


  w:
    description: Workspace
    items:
      TAB: editor:focus
      d: workspace:close
      f: file-explorer:open
      h: editor:focus-left
      i: editor:focus-right
      e: editor:focus-top
      n: editor:focus-bottom
      c: workspace:next-tab
      N: workspace:new-tab
      o: outline:open
      p: workspace:previous-tab
      P: workspace:toggle-pin
      s: workspace:split-horizontal
      S: workspace:toggle-stacked-tabs
      t: tag-pane:open
      u: workspace:undo-close-pane
      v: workspace:split-vertical
      L: app:toggle-left-sidebar
      r: app:toggle-right-sidebar
      R: app:toggle-ribbon
      w: workspace:open-in-new-window
      W: workspace:move-to-new-window

      x:
        description: Close
        items:
          g: workspace:close-tab-group
          G: workspace:close-others-tab-group
          t: workspace:close
          T: workspace:close-others
          w: workspace:close-window

       # workspace:goto-tab-1
       # workspace:goto-tab-2
       # workspace:goto-tab-3
       # workspace:goto-tab-4
       # workspace:goto-tab-5
       # workspace:goto-tab-6
       # workspace:goto-tab-7
       # workspace:goto-tab-8
       # workspace:goto-last-tab

       # workspace:show-trash

  f:
    description: File
    items:
      a: markdown:add-alias
      c: workspace:copy-path
      C: workspace:copy-url
      d: app:delete-file
      m: file-explorer:move-file
      o: open-with-default-app:open
      O: open-with-default-app:show
      r: editor:open-search-replace
      R: workspace:edit-file-title
      s: editor:save-file
      t: file-explorer:reveal-active-file
      T: tag-pane:open
      u: outline:open-for-current
      /: editor:open-search
      h: darlal-switcher-plus:switcher-plus:open-related-items

  c:
    description: New/Create
    items:
      d: file-explorer:duplicate-file
      n: file-explorer:new-file
      N: file-explorer:new-file-in-current-tab
      r: file-explorer:new-file-in-new-pane


  p:
    description: Properties
    items:
      a: markdown:add-metadata-property
      e: markdown:edit-metadata-property
      c: markdown:clear-metadata-properties

  x:
    description: Text
    items:
      b: editor:toggle-bold
      C: editor:toggle-code
      c: editor:toggle-comments
      d: editor:delete-paragraph
      F: editor:clear-formatting
      i: editor:toggle-italics
      p: editor:insert-codeblock
      q: editor:toggle-blockquote
      s: editor:toggle-strikethrough
      l: editor:toggle-bullet-list
      H: editor:toggle-highlight
      M: editor:toggle-inline-math
      o: editor:insert-callout

      # editor:set-heading
      # editor:set-heading-0
      # editor:set-heading-1
      # editor:set-heading-2
      # editor:set-heading-3
      # editor:set-heading-4
      # editor:set-heading-5
      # editor:set-heading-6
      # editor:rename-heading

      # editor:swap-line-down
      # editor:swap-line-up

      # editor:toggle-bullet-list
      # editor:toggle-checklist-status
      # editor:toggle-numbered-list
      # editor:cycle-list-checklist

  # i:
  #   description: Insert
  #   items:
  #     a: editor:attach-file
  #     c: editor:insert-codeblock
  #     C: editor:insert-callout
  #     e: editor:insert-embed
  #     l: editor:insert-link
  #     L: editor:insert-wikilink
  #     m: editor:insert-mathblock
  #     r: editor:insert-horizontal-rule
  #     T: editor:insert-tag

  #     t:
  #       description: Template
  #       items:
  #         t: insert-template
  #         d: insert-current-date
  #         T: insert-current-time

  t:
    description: +Toggle
    items:
      c: editor:toggle-comments
      f: editor:toggle-fold
      F: editor:toggle-fold-properties
      h: editor:toggle-highlight
      i: editor:toggle-inline-math
      l: editor:toggle-line-numbers
      m: editor:toggle-math
      p: editor:toggle-preview
      s: editor:toggle-spellcheck
      t: editor:toggle-sidebar
      w: editor:toggle-wrap

  T:
    description: Table
    items:
      h: editor:table-col-left
      l: editor:table-col-right
      k: editor:table-row-up
      j: editor:table-row-down
      c: editor:table-col-after
      C: editor:table-col-before
      r: editor:table-row-after
      R: editor:table-row-before
      v: editor:table-row-copy
      V: editor:table-col-copy
      i: editor:insert-table

      d:
        description: Delete
        items:
          c: editor:table-col-delete
          r: editor:table-row-delete

      a:
        description: Align
        items:
          c: editor:table-col-align-center
          l: editor:table-col-align-left
          r: editor:table-col-align-right

  v:
    description: View
    items:
      p: editor:toggle-source
      r: markdown:toggle-preview
      s: editor:toggle-spellcheck
      T: window:toggle-always-on-top

      # window:reset-zoom
      # window:zoom-in
      # window:zoom-out

  # "Workspaces" core plugin
  n:
    description: Layout
    items:
      l: workspaces:save-and-load
      L: workspaces:load
      o: workspaces:open-modal
      s: workspaces:save

# editor:toggle-fold-properties
# editor:toggle-fold
# editor:unfold-all
# editor:fold-all
# editor:fold-less
# editor:fold-more

# editor:follow-link
# editor:open-link-in-new-leaf
# editor:open-link-in-new-split
# editor:open-link-in-new-window
